---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: silvercachy
description: Silverblue image based on BlueBuild's base images with CachyOS kernel and Nvidia
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: 43

modules:
  # Copy necessary system files
  - type: files
    files:
      - source: system
        destination: /

  # Minimal base image without extra GUI or CLI tools
  - type: dnf
    remove:
      auto-remove: true
      packages:
        - firefox
        - firefox-langpacks
        - htop
        - nvtop
        - gnome-software
        - gnome-tour
        - ptyxis
        - gnome-system-monitor
        - malcontent-control
        - gnome-disk-utility
        - gnome-color-manager
        - yelp
        - gnome-shell-extension-background-logo
    install:
      skip-unavailable: true
      packages:
        - gamemode
        - adw-gtk3-theme

  # AppIndicator and KStatusNotifierItem Support
  - type: gnome-extensions
    install:
      - 615 

  # Minimal set of apps to be able to install other apps
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - io.github.kolunmi.Bazaar
          - app.devsuite.Ptyxis
      - scope: user

  # Expose audio group to users
  - type: script
    snippets:
      - 'grep -E "^audio:" /usr/lib/group >> /etc/group'

  # CachyOS Addons
  - from-file: cachyos.yml
  
  # Nvidia modules and userspace
  - from-file: nvidia.yml

  # Needed services
  - type: systemd
    system:
      enabled:
        - podman.socket
        - flatpak-settings-firstboot.service
        - mok-enroll-firstboot.service
        - hostname-firstboot.service

  # Sign kernel and modules recursively
  - type: script
    env:
      CERT: /usr/share/silvercachy/MOK.pem
      KEY: /tmp/certs/MOK.priv
    secrets:
      - type: file
        source: ./MOK.priv
        mount: 
          type: file
          destination: /tmp/certs/MOK.priv
    scripts:
      - sign.sh

  # Re-build initramfs
  - type: script
    scripts:
      - initramfs.sh

  # Set OS name
  - type: os-release
    properties:
      ID: silvercachy
      ID_LIKE: fedora
      NAME: SilverCachy
      PRETTY_NAME: SilverCachy - Fedora Silverblue with CachyOS Kernel

  - type: signing
